# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Who do you love?'
        # Default value if no value is explicitly provided
        default: 'Everybody'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Workflow steps
  greet:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        CI_COMMIT_REF_NAME="Test123"
        bash --version
        echo "Hello ${{ github.event.inputs.name }}"
        echo "Echoing Secret..."
        echo "Secret: ${{ secrets.SIMPLE_SECRET }}"
        echo "Start"
        testValue="Test Data"
        echo "Test Data: $testValue"        
        pwdstr="${{ secrets.SSH_HOST }}"
        echo "pwdstr: $pwdstr"
        pwdlen=${#pwdstr}
        echo "PWD Len: $pwdlen"      
        echo $pwdstr | cut -c1-1
        echo $pwdstr | cut -c2-$((pwdlen-0))
        echo "End"
        BUILD_JSON=$(jq -c -n \
          --arg CI_COMMIT_REF_NAME "$CI_COMMIT_REF_NAME" \
          '{"resources": { "repositories": { "self": { "refName": $CI_COMMIT_REF_NAME } }}}')
        echo $BUILD_JSON
        #exit 1
        
    - name: Install SSH Key
      #if: ${{ false }}
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      #if: ${{ false }}
      #SSH_HOST
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      #run: ssh-keyscan -H 71.209.201.240 >> ~/.ssh/known_hosts        
        

    - name: Deploy with rsync
      #if: ${{ false }}
      run: |
        buildId=$(ssh rzmudzinski@${{ secrets.SSH_HOST }} ./cicd/init_build.sh)
        echo "Build Id: $buildId"
        #ssh rzmudzinski@${{ secrets.SSH_HOST }} ./cicd/build.sh
      
