# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Who do you love?'
        # Default value if no value is explicitly provided
        default: 'Everybody'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Workflow steps
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install SSH Key
      if: ${{ false }}
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      if: ${{ false }}
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts        
        
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ github.event.inputs.name }}"
        echo "Echoing Secret..."
        echo "Secret: ${{ secrets.SIMPLE_SECRET }}"
        echo "Start"
        pwdstr=$(secrets.SIMPLE_SECRET)
        pwdlen=${#pwdstr}
        echo "PWD Len: $pwdlen"
        echo $(P12password) | cut -c1-4
        echo "End"
        #exit 1

    - name: Deploy with rsync
      if: ${{ false }}
      run: ssh rzmudzinski@${{ secrets.SSH_HOST }} ./cicd/build.sh
      
